[versions]
kotlinxSerialization = "1.2.1"
kotlinTestJs = "1.5.21"

[libraries]
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlinTestJs" }

kotlinx-html = "org.jetbrains.kotlinx:kotlinx-html:0.7.3"
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
