name: alpha release auto merge
on:
  push:
    branches:
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release/alpha/1.0.0
      - name: Environment detector
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Reset alpha branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "[Auto merge] Update alpha release ${{ steps.vars.outputs.branch }}-$GITHUB_SHA"
          branch: auto-merge-alpha-release
          labels: "bot"
