name: Publish Alpha release
on:
  push:
    branches:
      - release/alpha/**
jobs:
  publish_alpha_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Environment detector
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha::$(git rev-parse HEAD)"
      - run: ./gradlew assemble
      - name: Publish release
        run: |
          dir=$PWD
          git clone "${{ secrets.TARGET_ALPHA_REMOTE_GIT }}" "../working"
          cd ../working
          sh tools/release.sh "$dir/build/distributions" "${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha }}"
