name: Publish Alpha release
on:
  push:
    branches:
      - release/alpha/**
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      git_sha: ${{ steps.vars.outputs.sha }}
      git_branch: ${{ steps.vars.outputs.branch }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Cache local maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Environment detector
        id: vars
        shell: bash
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      - run: ./gradlew assemble
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: alpha-release-artifact
          path: build/distributions

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "${{ needs.build.outputs.git_branch }}"
      - name: Get built artifact
        uses: actions/download-artifact@v3
        with: 
          name: alpha-release-artifact
          path: distributions
      - name: Fetch current alpha code
        run: git clone "${{ secrets.TARGET_ALPHA_REMOTE_GIT }}" "../working"
      - name: Publish release
        working-directory: working
        run: |
          sh tools/release.sh "../distributions" "${{ needs.build.outputs.git_branch }}-${{ needs.build.outputs.git_sha }}"
