name: Build artifact
on: [ push ]
jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew assemble
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: build/distributions/
