name: Code health check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew test --continue
      - name: Clean up test result
        if: failure()
        run: sh tools/devops/remove_success_test_report
      - name: Publish test result
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-result
          path: |
            build/reports/tests/
            app/build/reports/tests/
            libs/**/reports/tests/

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew ktlint

  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew assemble
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: build/distributions/
