name: Publish Product release
on:
  workflow_dispatch:
  push:
    branches:
      - release/product
jobs:
  publish_product_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Environment detector
        id: vars
        shell: bash
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      - run: ./gradlew assemble
      - name: Publish release
        run: |
          dir=$PWD
          git clone "${{ secrets.TARGET_PRODUCT_REMOTE_GIT }}" "../working"
          cd ../working
          sh tools/release.sh "$dir/build/distributions" "${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha }}"
