name: Publish release
on:
  push:
    branches:
      - release/alpha/**
jobs:
  publish_alpha_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Environment detector
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha::$(git rev-parse HEAD)"
      - run: ./gradlew assemble
      - name: Publish release
        run: |
          dir=$PWD
          remote="${{ secrets.ALPHA_DESTINATION_USERNAME }}/${{ secrets.ALPHA_DESTINATION_REPOSITORY }}.git"
          auth="tuanchauict:${{secrets.API_TOKEN_GITHUB}}"
          git clone "https://$auth@github.com/$remote" "../working"
          cd ../working
          sh tools/release.sh "$dir/build/distributions" "${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha }}"
